// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/empty.proto

// Protobuf Java Version: 3.25.1
package com.google.protobuf;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Empty)
    com.google.protobuf.MessageOrBuilder {
}
